advanced2/backend/models/SystemForm.php
<?php
namespace backend\models;

use Yii;
use yii\base\Model;

/**
 * Login form
 */
class SystemForm extends Model
{
   public $adminEmail;
   public $adminName;
   public $adminTel;
   public $adminCopy;
   public $adminIcp;
   public $adminAddress;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['adminName','adminEmail','adminTel','adminCopy','adminIcp','adminAddress'], 'required','message'=>'不能为空'],
            ['adminEmail','email','message'=>'邮箱格式不正确']
        ];
    }
    public function attributeLabels(){
        return [
           'adminEmail'=>'网站联系邮箱：',
            'adminName'=>'联系人：',
            'adminTel'=>'联系电话：',
            'adminCopy'=>'网站版权：',
            'adminIcp'=>'备案ICP：',
            'adminAddress'=>'地址：'
        ];
    }
}

advanced2/backend/controllers/SystemController.php
<?php
namespace backend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;
use yii\rbac\Item;
use yii\rbac\Rule;
use backend\models\RoleForm;
use backend\models\PermissionForm;
use backend\models\SystemForm;
use backend\models\Auth;
/**
 * Site controller
 */
class SystemController extends Controller
{
    public $layout='main2';
    public function actionUpdate(){
        $model=new SystemForm();
        if(Yii::$app->request->isPost){
            $arr=Yii::$app->request->post('SystemForm');
            $path=$_SERVER['DOCUMENT_ROOT'].'/../config/params.php';
            $config=var_export(array_merge(include($path),$arr),true);
            $str="<?php \n return ";
            $config=$str.$config.";";
            file_put_contents($path,$config);
        }
        return $this->render('update',['model'=>$model]);
    }
    public function actionRbac(){
        $modelRole=new RoleForm();
        $modelRole->isNewRecord='添加';
        $modelPermission=new PermissionForm();
        $modelPermission->isNewRecord="添加";
        return $this->render('index',['modelRole'=>$modelRole,'modelPermission'=>$modelPermission]);
    }
    public function actionRole(){
        $auth=Yii::$app->authManager;
        if(Yii::$app->request->isPost){
            $data=Yii::$app->request->post('RoleForm');
            $author = $auth->createRole($data['name']);
            $author->description='创建了'.$data['name'].'的角色';
            $auth->add($author);
        }
        return $this->redirect(['rbac']);
    }
    public function actionPermission(){
        $auth=Yii::$app->authManager;
        if(Yii::$app->request->isPost){
            $data=Yii::$app->request->post('PermissionForm');
            $author = $auth->createPermission($data['name']);
            $author->description='创建了'.$data['name'].'的权限';
            $auth->add($author);
        }
        return $this->redirect(['rbac']);
    }
    public function actionAddChild($name){
        $auth = Yii::$app->authManager;
        if(Yii::$app->request->post()){
            //如果表中存在   则删除后再赋权
            if(Yii::$app->db->createCommand('select count(1) as num from `auth_item_child` where parent=:name')->bindValue(":name",$name)->queryOne()['num']){
                Yii::$app->db->createCommand()->delete('auth_item_child','parent=:name',[':name'=>$name])->execute();
            }
            $parent = $auth->createRole($name);
            foreach(Yii::$app->request->post('Auth')['name'] as $val){
                $child = $auth->createPermission($val);
                $auth->addChild($parent,$child);
            }
            return $this->redirect(['rbac']);
        }
        return $this->render('role_permission_form',['model'=>Auth::findOne(['name'=>$name]),'data'=>Auth::findAll(['type'=>2])]);
    }
    public function actionRoleDel($name){
        if(Auth::findOne(['name'=>$name])->delete() || Yii::$app->db->createCommand()->delete('auth_item_child','parent=:name',[':name'=>$name])->execute()){
            return $this->redirect(['rbac']);
        }else{
            die("<script>alert('删除失败！');location.href='".Url::toRoute('system/rbac')."'</script>");
        }
    }
}

advanced2/backend/views/system/index.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use backend\assets\RoleAsset;
use yii\bootstrap\ActiveForm;
$this->title='权限管理';
$this->params['breadcrumbs'][] = $this->title;
RoleAsset::register($this);
?>
<div class="main-wrap">
    <ul class="nav nav-tabs" style="height: 50px">
        <li class="active"><a href="#role_list" data-toggle="tab">角色列表</a></li>
        <li><a href="#role_add" data-toggle="tab">角色添加</a></li>
        <li><a href="#node_add" data-toggle="tab">权限添加</a></li>
        <li><a href="#node_list" data-toggle="tab">权限列表</a></li>
    </ul>
    <div class="result-content tab-content" id="myTabContent">
    <div class="tab-pane fade" id="role_list">
        <?=$this->render('role_list')?>
    </div>
    <div class="tab-pane fade" id="role_add">
        <?=$this->render('role_form',['model'=>$modelRole])?>
    </div>
    <div class="tab-pane fade" id="node_add">
        <?=$this->render('permission_form',['model'=>$modelPermission]);?>
    </div>
    <div class="tab-pane fade" id="node_list">
        <?=$this->render('permission_list');?>
    </div>

</div>
</div>

advanced2/backend/views/system/permission_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Igoods */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="permission-form">
    <?php $form = ActiveForm::begin([
        'id'=>'PermissionForm',
        'action'=>'index.php?r=system/permission'
    ]); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '添加' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

advanced2/backend/views/system/permission_list.php
<?php
/**
 * Created by PhpStorm.
 * User: 17985
 * Date: 2017/9/13
 * Time: 15:37
 */
use yii\db\Query;
$data=(new Query())
    ->select('*')
    ->from('auth_item')
    ->where(['type'=>2])
    ->all();
?>

    <table class="table table-hover">
        <thead>
        <tr>
            <th>权限</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
      <?php foreach($data as $v){?>
        <tr>
            <td><?=$v['name']?></td>
            <td><a href="">删除</a> | <a href="">修改</a></td>
        </tr>
        <?php }?>
        </tbody>
    </table>

advanced2/backend/views/system/role_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Igoods */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="role-form">
    <?php $form = ActiveForm::begin([
        'id'=>'RoleForm',
        'action'=>'index.php?r=system/role'
    ]); ?>

    <?= $form->field($model, 'name')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? '添加' : '修改', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>

</div>

advanced2/backend/views/system/role_list.php
<?php
/**
 * Created by PhpStorm.
 * User: 17985
 * Date: 2017/9/13
 * Time: 15:37
 */
use yii\db\Query;
use yii\helpers\Url;
$data=(new Query())
    ->select('*')
    ->from('auth_item')
    ->where(['type'=>1])
    ->all();
?>
    <table class="table table-hover">
        <thead>
        <tr>
            <th>角色</th>
            <th>拥有权限</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
      <?php foreach($data as $v){?>
        <tr>
            <td><?=$v['name']?></td>
            <td>
                <?php
                $str='';
                $sign='';
                $arr=(new Query())
                        ->select('child')
                        ->from('auth_item_child')
                        ->where(['parent'=>$v['name']])
                        ->all();
                        foreach($arr as $val){
                            $str.=$sign.$val['child'];
                            $sign=',';
                        }
                echo $str;
                ?>
            </td>
            <td><a href="<?=Url::toRoute(['system/add-child','name'=>$v['name']])?>">赋权</a> | <a href="<?=Url::toRoute(['system/role-del','name'=>$v['name']])?>">删除</a></td>
        </tr>
        <?php }?>
        </tbody>
    </table>

advanced2/backend/views/system/role_permission_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\db\Query;
/* @var $this yii\web\View */
/* @var $model app\models\Igoods */
/* @var $form yii\widgets\ActiveForm */
$this->title='角色赋权';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="main-wrap">
<div class="role-permission-form">
    <?php $form = ActiveForm::begin([
        'id'=>'RolePermissionForm',
        'action'=>Url::toRoute(['system/add-child','name'=>$model['name']])
    ]); ?>

    <?= $form->field($model, 'name')->textInput(['disabled'=>'disabled']) ?>
    <?php foreach($data as $key=>$val){?>
        <?php $aa[$val['name']]=$val['name']?>
    <?php }?>
    <?php
    $array=[];
    $arr=(new Query())
        ->select('child')
        ->from('auth_item_child')
        ->where(['parent'=>$model['name']])
        ->all();
    foreach($arr as $v){
        $array[]=$v['child'];
    }
    ?>
    <?php $model->name=$array;?>
    <?=$form->field($model,'name')->checkboxList($aa)?>
    <div class="form-group">
        <?= Html::submitButton('赋权', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>
    </div>

advanced2/backend/views/system/update.php
<?php
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title='系统设置';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="system-update">
    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin([
                'id' => 'system-form',
            ]); ?>
            <?php $model->adminEmail=Yii::$app->params['adminEmail']?>
            <?=$form->field($model,'adminEmail')->textInput(['placeholder'=>'请输入您正确邮箱'])?>
            <?php $model->adminName=Yii::$app->params['adminName']?>
            <?=$form->field($model,'adminName')->textInput(['placeholder'=>'请输入您正确联系人'])?>
            <?php $model->adminTel=Yii::$app->params['adminTel']?>
            <?=$form->field($model,'adminTel')->textInput(['placeholder'=>'请输入您正确联系电话'])?>
            <?php $model->adminCopy=Yii::$app->params['adminCopy']?>
            <?=$form->field($model,'adminCopy')->textInput(['placeholder'=>'请输入您正确版权信息'])?>
            <?php $model->adminIcp=Yii::$app->params['adminIcp']?>
            <?=$form->field($model,'adminIcp')->textInput(['placeholder'=>'请输入您正确备案信息'])?>
            <?php $model->adminAddress=Yii::$app->params['adminAddress']?>
            <?=$form->field($model,'adminAddress')->textInput(['placeholder'=>'请输入您正确地址'])?>
            <div class="form-group">
                <?= Html::submitButton('配置', ['class' => 'btn btn-primary', 'name' => 'system-button']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>